version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=no_country
      - SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      - ALGORITHM = "HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES = 30
      - IMEGEN_DIR=/app/frontend/public/imagenes/perfil/
      - IMEGEN_DIR2=/app/frontend/public/imagenes/details/
      - CORS_ORIGIN = http://localhost:5173/
      - MYSQL_USER =root
      - MYSQL_PASSWORD =root
      - MYSQL_DB =no_country
    depends_on:
      - db
    entrypoint:
      [
        './wait-for-it.sh',
        'db:3306',
        '--',
        'uvicorn',
        'Backend.main:main_app',
        '--host',
        '0.0.0.0',
        '--port',
        '8000'
      ]
    volumes:
      - shared-data:/app/frontend/public

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=http://127.0.0.1:8000
        - VITE_IMG_FOLDER_URL=/imagenes
    ports:
      - '5173:80'
    volumes:
      - shared-data:/app/frontend/public

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: no_country
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  shared-data:
