"""Cambiar nombre de columna

Revision ID: 67f989e79533
Revises: 
Create Date: 2024-07-18 15:27:54.640279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67f989e79533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudadopcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=250), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('type_appli', sa.String(length=250), nullable=True),
    sa.Column('employm_situ', sa.String(length=250), nullable=True),
    sa.Column('type_of_house', sa.String(length=250), nullable=True),
    sa.Column('income_range', sa.String(length=250), nullable=True),
    sa.Column('yard', sa.String(length=250), nullable=True),
    sa.Column('mt2_yard', sa.Integer(), nullable=True),
    sa.Column('another_pet', sa.String(length=250), nullable=True),
    sa.Column('another_pet_desc', sa.String(length=250), nullable=True),
    sa.Column('status_appli', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_column('usuario', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('surname', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('usuario', 'username')
    op.drop_table('solicitudadopcion')
    # ### end Alembic commands ###
